### PR TITLE
Add any type to test context (for TypeScript)

### PR DESCRIPTION
**Pull request by skovy**
When running the transform that converts `this` usage into `testContext` it inserts `let testContext`.

If running in a TypeScript codebase with the compiler option [`noImplicitAny`](https://www.typescriptlang.org/docs/handbook/compiler-options.html) enabled this will result in compiler errors.

This pull request will add the `any` type annotation to `let testContext` to explicitly define this value as `any`:

```typescript
let testContext: any;
```

It's probably unrealistic that the correct typings could be automatically generated.

This is done by checking if the `parser` option is `tsx` or `ts`.

This also fixes a type issue introduced in https://github.com/skovhus/jest-codemods/pull/183.

### CODE REVIEW

**Comment by skovy** [comment]
> Why is the null needed here?

Oh, in `src/utils/test-helpers.ts`? 

There's a type error in the tests that wasn't caught in the last pull request (https://github.com/skovhus/jest-codemods/pull/183). I'm happy to undo and move to its own pull request if you'd prefer to keep changes focused 👍 

```
src/transformers/expect-js.test.ts:23:26 - error TS2345: Argument of type 'string | void' is not assignable to parameter of type 'string'.
  Type 'void' is not assignable to type 'string'.

23     expect(wrappedPlugin(result, options)).toBe(result)
                            ~~~~~~

src/transformers/expect.test.ts:23:26 - error TS2345: Argument of type 'string | void' is not assignable to parameter of type 'string'.
  Type 'void' is not assignable to type 'string'.

23     expect(wrappedPlugin(result, options)).toBe(result)
```

I'm also open to other approaches, such as casting `as string`, or returning a different default.
